
import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  output: 'export',
  /* config options here */
  poweredByHeader: false,
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'placehold.co',
        port: '',
        pathname: '/**',
      },
    ],
    unoptimized: true,
  },
  trailingSlash: true,
  // Custom webpack config to handle Domo's restriction on special characters in filenames
  webpack: (config, { isServer }) => {
    if (!isServer) {
      // Use [id] instead of [name] to avoid brackets in filenames often generated by Next.js
      // Domo Appstore does not allow [ ] in filenames
      // We use unique templates to prevent "Multiple chunks emit assets to the same filename" errors
      config.output.filename = 'static/chunks/[id].[contenthash].js';
      config.output.chunkFilename = 'static/chunks/[id].[chunkhash].js';
    }
    return config;
  },
};

export default nextConfig;
